### ISSUE TITLE
Vars for property names

### ISSUE THREAD

**Issue by ai** [postcss/postcss-simple-vars#13]
```css
a {
    $(prop): 1px;
}
```

**Comment by ai** [comment]
Fixed by @mahtd in PostCSS 5.0.5

**Comment by yuezk** [comment]
@ai Why this issue closed? I cloned this repo and added the following test case, but it failed. So am I wrong or the issue still exists?

```js
it('vars for property names', function () {
    test('$prop: width; a{ $(prop): 1px; }', 'a{ width: 1px }');
});
```

**Comment by ai** [comment]
Oops, released in 1.1

**Comment by CKGrafico** [comment]
Am I doing something wrong?
```
 $a: color;

  .color {
    $(a): red;
  }
```


```
(49:5) postcss-simple-vars: ....\map-utilities.css Undefined variable $a

  47 | 
  48 |   .color {
> 49 |     $(a): red;
     |     ^
  50 |   }
  51 | }
```

**Comment by sampullman** [comment]
@CKGrafico I'm not able to reproduce, the example you posted works fine for me with version `6.0.3`

**Comment by CKGrafico** [comment]
Finally understood my problem, I was using default postcss import and was not working, only worked to me with postcss-import plugin.

Sorry!
